### ISSUE TITLE
On timeliness stats, make it clear what the date "publisher first appeared in the statistical snapshot" is

### ISSUE THREAD

**Issue by stevieflow** [codeforIATI/analytics#33]
The timeliness stats rely on this date, so that only subsequent months are used to log and updates, and then work out the update frequency

This date is not displayed for any publisher, however.  This makes it difficult to understand - particularly for "new" publishers - which set of frequency measures apply

Hence, this is a request to publish this date, and then declare which band this publisher falls into

I think this could be a static column on the timeliness table, but also on the publisher page, if possible....

**Comment by andylolz** [comment]
So "when a publisher first appeared in the statistical snapshot" is when the dashboard first finds a transaction in the publisher’s data.

For a handful of the early publishers, this will be 2013-09-19 (the date the dashboard was switched on). For timeliness calculations, it’s acceptable that this is wrong, because they all end up in the "1 year or more" bucket anyway. If we were to show the full date, I think it would be best to put "2013-09-19 or earlier" for these.

The other potentially confusing thing about the date is: there is no guarantee it will agree with the first published date on the registry. That’s because the publisher may have:
 * created a registry account and not started publishing immediately
 * only published an org file initially (i.e. no transactions)
 * initially published an activity file that doesn’t contain transactions
 * initially published an activity file that is not valid XML, or is badly formatted (e.g. missing transaction dates)

Rather than showing the first published date, how about only showing the bands @stevieflow? So, a column that shows one of:
 * A year or more
 * 6 months to a year
 * 3 to 6 months
 * Less than 3 months

**Comment by andylolz** [comment]
This should be fixed in 05b2d6f.

**Comment by andylolz** [comment]
The fixed version is building here: https://github.com/codeforIATI/analytics/runs/2575757868?check_suite_focus=true

**Comment by stevieflow** [comment]
Thanks - it's really helpful, to start to see new publishers, and very old, dormant ones (for example)

I think the sort on that column sorts them into order of the bandings, too (rather than alphabetically)?

**Comment by stevieflow** [comment]
> I think the sort on that column sorts them into order of the bandings, too (rather than alphabetically)?

Actually, I see what you've done there, with the strings being order-able :) 

There's a very large cohort on "More than 1 year ago".  Any chance to further segment this this - to 1, 3 and 5 years (for example)?

**Comment by andylolz** [comment]
> There's a very large cohort on "More than 1 year ago". Any chance to further segment this this - to 1, 3 and 5 years (for example)?

Yeah… That is definitely doable. My one concern would be that the extra bands won’t correspond to [the bands here](https://analytics.codeforiati.org/timeliness.html#h_assesment)… What do you think, is that okay?

So the bands would be:
 * Less than 3 months ago
 * 3-6 months ago
 * 6-12 months ago
 * 1-3 years ago
 * 3-5 years ago
 * More than 5 years ago

Yeah, in fact, that seems much nicer!

**Comment by stevieflow** [comment]
Understood, but I think the reality is those original bands were made when IATI was into its third year.  We've moved on a bit since then :)

**Comment by andylolz** [comment]
Kk this should be sorted on dev shortly: https://analytics-dev.codeforiati.org/timeliness.html

**Comment by stevieflow** [comment]
Thanks.  Wow - sooo many publishers more than 5 years *and* less than annual 

We might want some metrics on these combinations btw - elaborating on the data in "Summary of Publisher Performance" (I can create a new issue)?

**Comment by andylolz** [comment]
> We might want some metrics on these combinations btw - elaborating on the data in "Summary of Publisher Performance"

Yeah, Good shout – faceting timeliness by first published is definitely interesting.

I am not exactly sure how we’d do this… We could replace the existing “Summary of Publisher Performance” table… Or create an additional table?

> (I can create a new issue)?

That would be great – thank you!

**Comment by andylolz** [comment]
I guess this one can be closed now.
